[features]
seeds = false
skip-lint = false

[programs.devnet]
web3_tickets = "35wzuQvuh6PkqoTe8sgZu8hx8cV4sG2G8h89zELaLmKD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/web3_tickets.js"
